disease_recommendations = {
    "Acne": "Wash your face twice daily with a gentle cleanser. Avoid squeezing pimples. Use non-comedogenic products.",
    "Actinic_Keratosis": "Use sunscreen daily and schedule regular checkups with a dermatologist. Early treatment helps prevent skin cancer.",
    "Benign_tumors": "Generally harmless. Monitor for any changes in size, color, or texture and consult a healthcare provider if needed.",
    "Bullous": "Avoid trauma to the skin and consult a dermatologist for diagnosis. Treatment may involve corticosteroids or immune therapy.",
    "Candidiasis": "Keep the affected area dry and clean. Use antifungal creams as prescribed. Avoid tight clothing.",
    "DrugEruption": "Stop the suspected medication immediately and consult a doctor. Don’t restart any drug without medical advice.",
    "Eczema": "Moisturize frequently, avoid harsh soaps, and identify triggers such as allergens or stress. Use prescribed topical steroids if needed.",
    "Infestations_Bites": "Use antihistamines or soothing creams to relieve itching. Seek medical help for persistent symptoms or infection.",
    "Lichen": "Manage stress and avoid scratching. Corticosteroid creams may help. A dermatologist should be consulted for chronic cases.",
    "Lupus": "Avoid sun exposure, manage stress, and stay hydrated. Follow up regularly with a rheumatologist or dermatologist.",
    "Moles": "Monitor for changes in shape, size, or color. See a dermatologist if any mole appears suspicious or itchy.",
    "Psoriasis": "Keep your skin moisturized and avoid known triggers. UV light therapy and prescribed treatments can reduce flare-ups.",
    "Rosacea": "Avoid spicy foods, alcohol, and extreme temperatures. Use gentle skincare products and prescribed topical medications.",
    "Seborrh_Keratoses": "Usually harmless. No treatment is required unless for cosmetic reasons or irritation. See a doctor for removal options.",
    "SkinCancer": "Seek immediate medical evaluation. Early detection and treatment are critical. Avoid direct sun exposure and use SPF 30+ sunscreen.",
    "Sun_Sunlight_Damage": "Apply broad-spectrum sunscreen daily, wear protective clothing, and avoid peak sun hours. Hydrate your skin regularly.",
    "Tinea": "Use antifungal creams or powders. Keep the area dry and avoid sharing personal items like towels or razors.",
    "A Normal Picture": "No abnormality detected. Maintain good hygiene and monitor your skin regularly for any changes.",
    "Vascular_Tumors": "Usually benign. Observe for any growth or bleeding and consult a specialist for further evaluation if necessary.",
    "Vasculitis": "Seek immediate medical care. It may indicate an underlying condition. Avoid triggers and follow prescribed treatments.",
    "Vitiligo": "Use sunscreen to protect depigmented skin. Cosmetic cover-ups or light therapy may help. Dermatological consultation is advised.",
    "Warts": "Avoid picking at warts and use over-the-counter salicylic acid or cryotherapy. Seek medical help if persistent or painful."
}
